#-------------------------------
# General Site Settings

title: Shaun Sweeney
description: Based in London, UK
email: shaun.sweeney@ucdconnect.ie

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Experience, url: '#work'}
- {name: Blog, url: '#blog'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: ""
  rel-author: 'http://www.linkedin.com/in/shaundsweeney/'


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

welcome: >
  **Welcome!**

blurb: >

  I'm 24 years old and I have recently graduated with a Masters degree in Energy Systems Engineering from University
  College Dublin, Ireland. I also have a Bachelors degree in Electrical & Electronic Engineering.
  I made this website in order to display my experiences in a personalised way and in order to learn
  some new software skills. On this website you will find details of the things that I am good at, my achievements, my work
  experience and a few comments from some people I have worked with in the past.


  To get to know me a bit better, here is a list of things that I can do/I am interested in:

skills:
- {name: 'Energy systems, power systems', value: '7'}
- {name: 'Connected, electrical transport systems', value: '8'}
- {name: 'Coding, software', value: '8'}
- {name: 'Statistics, data science, machine learning', value: '6'}
- {name: Project and team leadership, value: '9'}
- {name: Goal setting and achievement, value: '9'}
- {name: Attention to detail, value: '8'}
- {name: Communicate effectively, value: '8'}
- {name: Maths, value: '7'}
- {name: 'Smart cities, smart grids, economics', value: '7'}
- {name: 'Entrepreneurship, start-ups', value: '6'}
- {name: Control theory and optimisation, value: '8'}


endblurb: >


#-------------------------------
# Achievements Section

achievements:
- {name: Smart Class Competition, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Universitas 21 Summer School, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Energy Needs Ireland, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: University of Melbourne, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Ad Astra Academy Scholarship, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: All-Ireland Scholarship, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Elec Engineering Society, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Erasmus Student Network, folder: 'proj-8', file: 'work/proj-8.html'}

#-------------------------------
# Work Section
work:
- {name: Moixa Technology,
  folder: 'work-exp',
  file: 'work-exp/moixa',
  info: '',
  logo: 'moixa-logo.png'}
- {name: IBM Research,
  folder: 'work-exp',
  file: 'work-exp/ibm',
  info: '',
  logo: 'ibm-research-logo.png'}
- {name: Gondolaa,
  folder: 'work-exp',
  file: 'work-exp/gondolaa',
  info: '',
  logo: 'gondolaa-logo.png'}
- {name: EnerNOC,
  folder: 'work-exp',
  file: 'work-exp/enernoc',
  info: '',
  logo: 'enernoc-logo.jpg'}
- {name: ElectroRoute,
  folder: 'work-exp',
  file: 'work-exp/electroroute',
  info: '',
  logo: 'electroroute-logo.png'}
- {name: Deloitte,
  folder: 'work-exp',
  file: 'work-exp/deloitte',
  info: "",
  logo: 'deloitte-logo.jpg'}
- {name: Electricity Research Centre,
  folder: 'work-exp',
  file: 'work-exp/erc',
  info: '',
  logo: 'erc-logo.png'}

#-------------------------------
# Clients Section

clients:
- {avatar: 'aonghus.jpg',
  name: 'Dr. Aonghus Shortt',
  title: "Shaun's Manager at ElectroRoute, now Founder at FoodMarble",
  quote: '<p>Shaun is an incredibly capable and hard working guy. While at ElectroRoute, he completed some outlandishly complex projects, going above and beyond what could be expected of him. He was a key asset and he also happens to be a really nice guy.</p>',
  logo: 'electroroute-logo.png'}

- {avatar: 'tony.jpg',
  name: 'Tony Whittle',
  title: "Shaun's Manager at EnerNOC, Now manager of EnerNOC Global Operations",
  quote: '<p>Shaun joined my team as an intern just before I hired 8 full time employees to build the EMEA operations center. Shaun learned fast, asked the right questions, pointed to & solved problems quickly and was in a position where he really was leading organisational change. He was in charge of numerous process and productivity improvement projects which he completed with an exceptionally high attention to detail. We have invited him back whenever he is free to work with us.</p>',
  logo: 'enernoc-logo.jpg'}

- {avatar: 'nina.jpg',
  name: 'Nina Wiegers',
  title: 'Co-Founder, Gondolaa',
  quote: "<p>Since co-founding Gondolaa in May 2016, Shaun has shown an incredible attention to detail, the ability to filter and translate important information nodes into actionable tasks, the ability to identify and subsequently eliminate potential bottlenecks in planning and executing tasks and strategy, as well as absolutely accurate allocation of essential resources for efficient collaboration. Shaun features an integer, easy-going and admirable personality.</p>",
  logo: 'gondolaa-logo.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/shaundsweeney/'}
- {icon: 'twitter', link: 'https://twitter.com/shaun__sweeney'}
- {icon: 'facebook', link: 'https://www.facebook.com/shaunsweeney1993'}
- {icon: 'github', link: 'https://github.com/sweeneys'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
