#-------------------------------
# General Site Settings

title: Shaun Sweeney
description: Looking for opportunities!
email: shaun.sweeney@ucdconnect.ie

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Experience, url: '#work'}
- {name: Blog, url: '#blog'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: ""
  rel-author: 'http://www.linkedin.com/in/shaundsweeney/'


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

welcome: >
  **Welcome!**

blurb: >
  
  I'm Shaun! I'm 23 and I will graduate from University College Dublin, Ireland with a Masters degree
  in energy systems engineering in May 2017 and I'm really not sure what I want to do after that.
  I love to travel and meet new people, I love to get involved in very technical and detailed projects
  and I love to learn new things.  
  I also have an exemplary academic record (but that's boring).
  To emphasise how not sure I am about what I want to do after I graduate, here is a list of
  things that I can do/I am interested in:

skills:
- {name: Energy and power systems, value: '8'}
- {name: Collaborate as part of a high-functioning team, value: '9'}
- {name: Electrical transport, value: '5'}
- {name: Data science, value: '5'}
- {name: Programming, value: '7'}
- {name: Project and team leadership, value: '8'}
- {name: Working to achieve goals, value: '9'}
- {name: Attention to detail, value: '9'}
- {name: Maths, value: '8'}
- {name: Smart cities, value: '6'}


endblurb: >

  The cynic (logical thinker) in me appreciates the ridiculousness of using a grading
  system like above to describe such general terms (what do I even mean that I am an '8' at maths?!).
  As such please discount the whole skills rating section above.
  The truth is I'm pretty much interested in everything, I love a challenge and I thrive on 
  responsibility. If there is anything you think I would be good at (job, PhD, graduate programme, start-up, 
  work in a bar in Spain), I would be really interested to hear about it so please get in touch.


#-------------------------------
# Work Section

projects:
- {name: Smart Class Competition, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Universitas 21 Summer School, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Energy Needs Ireland, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: University of Melbourne, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Ad Astra Academy, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: All Ireland Scholarship, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Elecsoc, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Erasmus Student Network, folder: 'proj-8', file: 'work/proj-8.html'}


#-------------------------------
# Clients Section

clients:
- {avatar: 'aonghus.jpg',
  name: 'Dr. Aonghus Shortt',
  title: "Shaun's Manager at ElectroRoute, now Founder at FoodMarble",
  quote: '<p>Shaun is an incredibly capable and hard working guy. While at ElectroRoute, he completed some outlandishly complex projects, going above and beyond what could be expected of him. He was a key asset and he also happens to be a really nice guy.</p>',
  logo: 'electroroute-logo.png'}

- {avatar: 'tony.jpg',
  name: 'Tony Whittle',
  title: "Shaun's Manager at EnerNOC, Now manager of EnerNOC Global Operations",
  quote: '<p>Shaun joined my team as an intern just before I hired 8 full time employees to build the EMEA operations center. Shaun learned fast, asked the right questions, pointed to & solved problems quickly and was in a position where he really was leading organisational change. He was in charge of numerous process and productivity improvement projects which he completed with an exceptionally high attention to detail. We have invited him back whenever he is free to work with us.</p>',
  logo: 'enernoc-logo.jpg'}

- {avatar: 'nina.jpg',
  name: 'Nina Wiegers',
  title: 'Co-Founder, Gondolaa, now working with Shaun to prepare for EUXCEL challenge final pitchs',
  quote: "<p>Since co-founding Gondolaa in May 2016, Shaun has shown an incredible attention to detail, the ability to filter and translate important information nodes into actionable tasks, the ability to identify and subsequently eliminate potential bottlenecks in planning and executing tasks and strategy, as well as absolutely accurate allocation of essential resources for efficient collaboration. Shaun features an integer, easy-going and admirable personality.</p>", 
  logo: 'gondolaa-logo.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/shaundsweeney/'}
- {icon: 'twitter', link: 'https://twitter.com/shaun__sweeney'}
- {icon: 'facebook', link: 'https://www.facebook.com/shaunsweeney1993'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
