#-------------------------------
# General Site Settings

title: Shaun Sweeney
description: Energy Systems Engineering
email: shaun.sweeney@ucdconnect.ie

# NOTE: The Logo and Background image are defined in the all.sass document.

menu:
- {name: About Me, url: '#about-me'}
- {name: Experience, url: '#work'}
- {name: Blog, url: '#blog'}
- {name: Contact, url: '#contact'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: ""
  rel-author: 'http://www.linkedin.com/in/shaundsweeney/'


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

#google-analytics-ua: UA-XXXXXX-X

#-------------------------------
# About Section

# NOTE: The avatar is defined in the all.sass document.

welcome: >
  **Welcome!**

blurb: >
  
  I graduate in May 2017 with a masters degree in energy systems engineering. I'm not sure
  what I want to do after that but here are some of the things that I am interested in:

skills:
- {name: Data Science, value: '5'}
- {name: Collaborate as part of a high functioning team, value: '9'}
- {name: Attention to detail, value: '9'}
- {name: Team development, value: '9'}
- {name: Python, value: '7'}
- {name: Leadership, value: '7'}
- {name: Working to achieve goals, value: '9'}
- {name: Power Systems, value: '8'}

endblurb: >

  Testing 1000


#-------------------------------
# Work Section

projects:
- {name: Smart Class Competition, folder: 'proj-1', file: 'work/proj-1.html'}
- {name: Universitas 21 Summer School, folder: 'proj-2', file: 'work/proj-2.html'}
- {name: Energy Needs Ireland, folder: 'proj-3', file: 'work/proj-3.html'}
- {name: University of Melbourne, folder: 'proj-4', file: 'work/proj-4.html'}
- {name: Ad Astra Academy, folder: 'proj-5', file: 'work/proj-5.html'}
- {name: All Ireland Scholarship, folder: 'proj-6', file: 'work/proj-6.html'}
- {name: Elecsoc, folder: 'proj-7', file: 'work/proj-7.html'}
- {name: Erasmus Student Network, folder: 'proj-8', file: 'work/proj-8.html'}


#-------------------------------
# Clients Section

clients:
- {avatar: 'aonghus.jpg',
  name: 'Dr. Aonghus Shortt',
  title: "Shaun's Manager at ElectroRoute, now Founder at FoodMarble",
  quote: '<p>Shaun is an incredibly capable and hard working guy. While at ElectroRoute, he completed some outlandishly complex projects, going above and beyond what could be expected of him. He was a key asset and he also happens to be a really nice guy.</p>',
  logo: 'electroroute-logo.png'}

- {avatar: 'tony.jpg',
  name: 'Tony Whittle',
  title: "Shaun's Manager at EnerNOC, Now manager of EnerNOC Global Operations",
  quote: '<p>Shaun joined my team as an intern just before I hired 8 FTE to build the EMEA NOC. During the training he learned fast, asked the right questions, pointed to & solved problems quickly. During the next few months he communicated change and shared learnings with the entire team and took a position where he really was leading change. He did numerous process improvement projects all with an exceptionally high attention to detail. Shaun did a great job and we have invited him back whenever he is free to work with us.</p>',
  logo: 'enernoc-logo.jpg'}

- {avatar: 'nina.jpg',
  name: 'Nina Wiegers',
  title: 'Co-Founder, Gondolaa, now working with Shaun to prepare for EUXCEL challenge final pitchs',
  quote: "<p>Since co-founding Gondolaa in May 2016, Shaun has shown an incredible attention to detail, the ability to filter and translate important information nodes into actionable tasks, the ability to identify and subsequently eliminate potential bottlenecks in planning and executing tasks and strategy, absolutely accurate allocation of essential resources for efficient collaboration. Shaun features an integer, easy-going and admirable personality.</p>", 
  logo: 'gondolaa-logo.png'}


#-------------------------------
# Contact Section

social:
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/shaundsweeney/'}
- {icon: 'twitter', link: 'https://twitter.com/shaun__sweeney'}
- {icon: 'facebook', link: 'https://www.facebook.com/shaunsweeney1993'}


# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
